[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"


[otelcol]
source = "github"
github = "open-telemetry/opentelemetry-collector"
use_latest_release = true
prefix = "v"

[otelcol-contrib]
source = "github"
github = "open-telemetry/opentelemetry-collector-contrib"
use_latest_release = true
prefix = "v"
